### PR TITLE
s/Design Proposal/KEP

### PR DESCRIPTION
**Pull request by spiffxp**
Drop the link to test plan, that should now be part of KEP

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold
Let's not drop the link until the KEP template is actually updated to explicitly include it.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/enhancements/pull/690 for KEP template update

**Comment by justaugustus** [comment]
Yep. I'll release the hold on this once #703 merges.
/lgtm
/approve

**Pull request merged**
