### PR TITLE
pod-overhead: add beta criteria

### PR DESCRIPTION
**Pull request by egernst**
update KEP to better describe the graduation criteria for beta.

### CODE REVIEW

**Comment by jeremyrickard** [comment]
@egernst will also be adding _Test Plan_ info to this

**Comment by egernst** [comment]
@jeremyrickard @derekwaynecarr @tallclair - PTAL.

**Comment by egernst** [comment]
@dchen1107 - can you PTAL?

**Comment by derekwaynecarr** [comment]
thanks for the updates.

/approve
/lgtm

**Pull request merged**
