### PR TITLE
Add manual test for removal of endpoints

### PR DESCRIPTION
**Pull request by dashpole**
/assign @annajung @ehashman @dchen1107

### CODE REVIEW

**Review by ehashman — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
@ehashman looks like just a checklist update.

/approve
/hold ( please remove hold whenever you have enough reviews @ehashman )

**Comment by SergeyKanzhelev** [comment]
/lgtm

CC: @bobbypage

**Comment by bobbypage** [comment]
/lgtm

Thanks!

**Pull request merged**
