### PR TITLE
Bump volume populators milestone to 1.22

### PR DESCRIPTION
**Pull request by bswartz**

### CODE REVIEW

**Comment by reylejano** [comment]
Hi @saad-ali @bswartz , there is a second lgtm.
Feel free to cancel the hold if the second lgtm is sufficient for reviews on this PR

**Comment by sftim** [comment]
/retitle Bump volume populators milestone to 1.22
for clarity

**Comment by bswartz** [comment]
Based on discussion here: https://github.com/kubernetes/enhancements/pull/2552 we have decided to amend the KEP rather than merely bump the version. I will do that in another PR.

**Pull request closed without merging**
