### PR TITLE
Update Kubeadm Windows KEP for 1.16

### PR DESCRIPTION
**Pull request by ksubrmnn**
KEP PR for Issue #995

### CODE REVIEW

**Comment by ksubrmnn** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by ksubrmnn** [comment]
@PatrickLang @daschott

**Comment by timothysc** [comment]
/assign @neolit123 
/unassign @timothysc 

Lubomir will take point and has context on this one.

**Comment by neolit123** [comment]
/lgtm
/assign @timothysc 
Tim, only you, Lucas and Justin can approve KEP changes.
https://github.com/kubernetes/enhancements/blob/42785ccf362a15be4dee29a5dae740b8eee63afe/OWNERS_ALIASES#L42-L45

**Pull request merged**
