### PR TITLE
Fix note on complexity of maintaining mu(i,t)

### PR DESCRIPTION
**Pull request by MikeSpreitzer**

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@tkashem 
@deads2k

**Comment by MikeSpreitzer** [comment]
@adtac

**Comment by MikeSpreitzer** [comment]
The force-push to 4d4a3737 added an exposition of the straightforward way to find `mu_fair`, in response to https://github.com/kubernetes/enhancements/pull/2544/files#r585347091 .

**Comment by lavalamp** [comment]
Looks fine, but was it superceded by your other PR?

**Comment by MikeSpreitzer** [comment]
This was included in #2544

**Pull request closed without merging**
