### PR TITLE
Adding windows privileged containers KEP

### PR DESCRIPTION
**Pull request by ambguo**

### CODE REVIEW

**Comment by marosset** [comment]
Can you add a KEP.yaml as well based off of https://github.com/kubernetes/enhancements/blob/master/keps/NNNN-kep-template/kep.yaml

(I apologize that the other sig-windows KEPs don't have this yet, so we did not have any good examples to follow)

**Comment by kikisdeliveryservice** [comment]
This is for issue #1981 Also note that the dir name is incorrect here it should be `1981-windows-privileged-container-support`

**Comment by kikisdeliveryservice** [comment]
This is for issue #1981 Also note that the dir name is incorrect here it should be 1981-windows-privileged-container-support

cc: @kinarashah for review

**Comment by fasaxc** [comment]
Great to see this getting off the ground; looking forward to the day when we can ship Calico as a daemonset on Windows.

**Comment by marosset** [comment]
/lgtm
/appove

Merging this now in a provisional state.
We can iterate and get more reviews when we move this to implementable.

**Pull request merged**
