### PR TITLE
Mark KEP 2161 as implemented and stable

### PR DESCRIPTION
**Pull request by rosenhouse**
ref: https://github.com/kubernetes/kubernetes/pull/101342

### CODE REVIEW

**Comment by sftim** [comment]
Should https://github.com/kubernetes/enhancements/issues/2161 show this as tracked for v1.22?

**Comment by nikhita** [comment]
@sftim yes :)

[slack thread](https://kubernetes.slack.com/archives/C0EG7JC6T/p1620758373426700) about adding this to the enhancements tracking sheet

**Comment by lavalamp** [comment]
/lgtm
/approve

I haven't heard any complaints about this, so it seems fine.

**Pull request merged**
