### PR TITLE
Update sig-storage features as implemented

### PR DESCRIPTION
**Pull request by msau42**
Fixes: #557

### CODE REVIEW

**Comment by xing-yang** [comment]
It looks that verify failed because "sig-pm" mentioned in the following kep no longer exists?

https://github.com/kubernetes/enhancements/blob/master/keps/0001-kubernetes-enhancement-proposal-process.md

../../keps/0001-kubernetes-enhancement-proposal-process.md has an error: "error validating KEP metadata: \"owning-sig\" must be one of (committee-code-of-conduct,committee-product-security,committee-steering,sig-api-machinery,sig-apps,sig-architecture,sig-auth,sig-autoscaling,sig-cli,sig-cloud-provider,sig-cluster-lifecycle,sig-contributor-experience,sig-docs,sig-instrumentation,sig-multicluster,sig-network,sig-node,sig-release,sig-scalability,sig-scheduling,sig-service-catalog,sig-storage,sig-testing,sig-ui,sig-usability,sig-windows,ug-big-data,ug-vmware-users,wg-api-expression,wg-component-standard,wg-data-protection,wg-iot-edge,wg-k8s-infra,wg-lts,wg-machine-learning,wg-multitenancy,wg-policy,wg-security-audit) but it is a string: sig-pm"

**Comment by palnabarun** [comment]
SIG PM has been retired vide https://github.com/kubernetes/org/pull/1796

@justaugustus need your help here :slightly_smiling_face: 

/cc @justaugustus

**Comment by justaugustus** [comment]
@palnabarun -- thanks for the heads up. Will take a look tomorrow!

**Comment by spiffxp** [comment]
/retest
https://github.com/kubernetes/enhancements/pull/1699 merged, should fix

**Pull request merged**
