### PR TITLE
seed KEPs for sig-etcd

### PR DESCRIPTION
**Pull request by logicalhan**
- One-line PR description:

Seeding a folder for sig-etcd.

/cc @wenjiaswe @serathius @ahrtr @jmhbnz

### CODE REVIEW

**Review by wenjiaswe — APPROVED** [review]

**Review by jmhbnz — APPROVED** [review]
/approve

LGTM - Thanks for taking care of this setup @logicalhan.

**Review by ahrtr — APPROVED** [review]

**Review by serathius — APPROVED** [review]

**Review by mrbobbytables — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
