### PR TITLE
Migrate remaining SIG api-machinery KEP to new template

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #2220 

/assign @lavalamp @deads2k

### CODE REVIEW

**Review by justaugustus — COMMENTED** [review]
@wojtek-t -- Do we also want to add a symlink to prevent external 404s?

**Comment by wojtek-t** [comment]
> @wojtek-t -- Do we also want to add a symlink to prevent external 404s?

I don't see that being referenced from any meaningful place other than the newly-created issue (which I will update once the PR merges). So I don't think it's really needed

**Comment by justaugustus** [comment]
> I don't see that being referenced from any meaningful place other than the newly-created issue (which I will update once the PR merges). So I don't think it's really needed

SGTM!
/lgtm
/approve
/hold for SIG API Machinery

**Pull request merged**
