### PR TITLE
Mark RunAsGroup as GA

### PR DESCRIPTION
**Pull request by ehashman**
Closes #213.

/cc @krmayankk @annajung

### CODE REVIEW

**Comment by annajung** [comment]
Thanks Elana!
/lgtm

/assign @dchen1107

**Comment by krmayankk** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by sftim** [comment]
LGTM

**Review by mrunalp — APPROVED** [review]

**Comment by krmayankk** [comment]
thanks @ehashman

**Pull request merged**
