### PR TITLE
Mark KEP 1659 as "implemented"

### PR DESCRIPTION
**Pull request by thockin**
Clear out last "UNRESOLVED"

### CODE REVIEW

**Review by kikisdeliveryservice — COMMENTED** [review]
should the milestone in the kep.yaml also be cleared out? since it's moving from provisional-> implementable now, 1.19 seems incorrect there?

**Review by andrewsykim — COMMENTED** [review]
/lgtm

**Comment by thockin** [comment]
@kikisdeliveryservice this is a weird one because it's really not a code change.  I'll take your suggestion and just clear it out.

**Comment by thockin** [comment]
https://github.com/kubernetes/website/pull/24783 implements this, so we will have a race - implemented vs implementable :)

**Comment by thockin** [comment]
2nd commit pushed - this in now implemented

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

**Comment by thockin** [comment]
PTAL @ahg-g

**Comment by thockin** [comment]
@kikisdeliveryservice is there more I need to do to get KEP changes approved?

**Comment by kikisdeliveryservice** [comment]
> @kikisdeliveryservice is there more I need to do to get KEP changes approved?

Since this seems to be docs work/arch work done outside of the release milestones, I think it's fine to just mark it as implemented (if you're all satisfied) and after that merges close the tracking issue here: https://github.com/kubernetes/enhancements/issues/1659

**Comment by thockin** [comment]
Yeah, this is not release-locked :)

Thanks

**Pull request merged**
