### PR TITLE
kubeadm remove clusterstatus KEP: Make minor clarifications

### PR DESCRIPTION
**Pull request by dlipovetsky**
/assign @fabriziopandini

### CODE REVIEW

**Comment by dlipovetsky** [comment]
/hold

My apologies, I confused myself. The KubeadmControlPlane controller doesn't use ClusterStatus as the source of truth--it checks the etcd health by talking to each static Pod. However, the controller will have to update ClusterStatus when removing a node, because it will not run (or, if the node is offline, cannot run)  `kubeadm reset`.

I will update my comments to reflect this.

**Comment by neolit123** [comment]
/remove-lifecycle stale
@fabriziopandini @dlipovetsky hi, is this PR still needed?

**Comment by dlipovetsky** [comment]
Thanks for reminding me. I removed the part about Cluster API. Should be correct now.

**Pull request merged**
