### PR TITLE
cleanup(enhancements): typo

### PR DESCRIPTION
**Pull request by yuzhiquan**
cleanup(enhancements): typo

### CODE REVIEW

**Comment by yuzhiquan** [comment]
Gently ping @dchen1107 @derekwaynecarr

**Comment by yuzhiquan** [comment]
Gently ping @dchen1107 @derekwaynecarr

**Comment by yuzhiquan** [comment]
Would you mind? @feiskyer

**Comment by yuzhiquan** [comment]
> looks good, thanks for the cleanup
> 
> /lgtm
> /ok-to-test

thanks.
and /assign @dchen1107

**Comment by justaugustus** [comment]
Thanks!
/approve

**Pull request merged**
