### PR TITLE
Update KEP template to reference required conformance tests.

### PR DESCRIPTION
**Pull request by johnbelamaric**

### CODE REVIEW

**Comment by johnbelamaric** [comment]
@kubernetes/cncf-conformance-wg

**Comment by WilliamDenniss** [comment]
+1

**Comment by hh** [comment]
:+1: Thanks for creating this @johnbelamaric

**Comment by spiffxp** [comment]
/cc @justaugustus 
ref https://github.com/kubernetes/enhancements/pull/703

**Comment by justaugustus** [comment]
Thanks for adding some additional context there, @johnbelamaric.
/lgtm
/approve

**Comment by justaugustus** [comment]
@johnbelamaric -- Thanks again for the PR! I've squashed and pulled your changes into #703, so I'm closing this out.

/close

**Pull request closed without merging**
