### PR TITLE
Server-side apply: Create flag to get managedFields

### PR DESCRIPTION
**Pull request by apelisse**
cc @kwiesmueller @jennybuckley @liggitt

### CODE REVIEW

**Comment by kwiesmueller** [comment]
I like it!
Does this address the scalability issues we saw?

**Comment by liggitt** [comment]
partially... for every round trip, there are two serializations:

Read path:
* read from etcd, decode into in-memory in apiserver
* encode for API client

Write path:
* read from incoming API request, decode into in-memory in apiserver
* read from etcd, decode into in-memory in apiserver
* compare resourceVersion, etc
* encode new object for etcd

This change would help the read path, but not the write path

**Comment by kwiesmueller** [comment]
Okay, but the write path is no longer so much different from before we had managedFields, is it?

**Comment by apelisse** [comment]
Yeah, this is mostly helping reads, not writes. The apiserver is the only component that pays the write cost of SSA, all components are paying the read (if we don't add this flag). Especially on big clusters, we do tend to have insanely big reads (thousands of pods/nodes etc ...).

**Comment by apelisse** [comment]
New thought that I have: We need to decide whether admission chain webhook would get the fields or not (or provide an option for them to decide). I suppose we could add a new field in the WebhookConfiguration that would default to no.

**Comment by apelisse** [comment]
I've added a paragraph to talk about webhooks

**Comment by apelisse** [comment]
We also need to consider serialization cache. I'll add a paragraph about that.

**Comment by apelisse** [comment]
@wojtek-t Any opinions on how this affect serialization cache and how we can address it?

**Comment by kwiesmueller** [comment]
@apelisse is this still a thing?
/remove-lifecycle rotten

**Comment by apelisse** [comment]
No that's irrelevant now.

**Pull request closed without merging**
