### PR TITLE
Mark kubectl-diff as implemented

### PR DESCRIPTION
**Pull request by apelisse**
cc @julianvmodesto @palnabarun

Fixes #491

### CODE REVIEW

**Comment by apelisse** [comment]
Fixes #491

**Comment by palnabarun** [comment]
/lgtm

(on behalf of 1.18 Enhancements Team)

**Comment by palnabarun** [comment]
Thank you @apelisse

**Comment by palnabarun** [comment]
/assign @pwittrock

(for approval)

**Pull request merged**
