### PR TITLE
KEP: add ReadOnlyBindAddress to KubeletConfiguration.

### PR DESCRIPTION
**Pull request by jfbai**
The KEP for #1208

### CODE REVIEW

**Comment by jfbai** [comment]
/cc @mtaufen 
/cc @mattjmcnaughton
/cc @yujuhong
/cc @tallclair

PTAL, thanks a lot. :)

**Comment by mtaufen** [comment]
@jfbai sorry for the rather long delay in addressing this KEP.

I asked @tallclair about this. The long term direction is still to get rid of the insecure server altogether, but this could be a reasonable in-between option as long as it doesn't distract from eventually removing the insecure server.

@tallclair also mentioned that localhost doesn't work for Windows containers, so this isn't necessarily a solution for Windows. 

I'm ok with this moving forward if we update the KEP to note that it isn't an alternative to someday removing the insecure server.

**Comment by jfbai** [comment]
> @jfbai sorry for the rather long delay in addressing this KEP.
> 
> I asked @tallclair about this. The long term direction is still to get rid of the insecure server altogether, but this could be a reasonable in-between option as long as it doesn't distract from eventually removing the insecure server.
> 
> @tallclair also mentioned that localhost doesn't work for Windows containers, so this isn't necessarily a solution for Windows.
> 
> I'm ok with this moving forward if we update the KEP to note that it isn't an alternative to someday removing the insecure server.

@mtaufen Thanks a lot, I add a note. PTAL.

**Comment by mtaufen** [comment]
Thanks. This LGTM. 

/lgtm

**Comment by mtaufen** [comment]
@derekwaynecarr @dchen1107 WDYT? Can you approve?

**Pull request closed without merging**
