### PR TITLE
Split kube-proxy into distinct components by ProxyMode, and adopt ComponentConfig

### PR DESCRIPTION
**Pull request by vllry**

### CODE REVIEW

**Comment by vllry** [comment]
Hey @Suhailpatel - you asked me at the summit about helping with splitting kube-proxy out of k/k. We're probably going to do some other cleanup work first before getting around to that, if you're interested.

**Comment by suhailpatel** [comment]
I would absolutely be interested in helping. I’ll have a read through the KEP and happy to take on tasks. 

It’ll be one of my first contributions so I’ll spend some time getting up to speed as much as I can.

**Comment by luxas** [comment]
xref: https://docs.google.com/document/d/1q0oIXUIEnFm6dSnAtZfnsvJCJL39x8ozVE6N4iGtaLw/edit#heading=h.d7jh5gr66xtr
similar but not the same.
These proposals need to be aligned though.

**Comment by rosti** [comment]
> xref: https://docs.google.com/document/d/1q0oIXUIEnFm6dSnAtZfnsvJCJL39x8ozVE6N4iGtaLw/edit#heading=h.d7jh5gr66xtr
> similar but not the same.

The actual submitted KEP, based on that proposal: #1104

**Pull request closed without merging**
